//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoping.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoteCreateObject", ReplyAction="*")]
        OnlineShoping.ServiceReference1.RemoteCreateObjectResponse RemoteCreateObject(OnlineShoping.ServiceReference1.RemoteCreateObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoteCreateObject", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.RemoteCreateObjectResponse> RemoteCreateObjectAsync(OnlineShoping.ServiceReference1.RemoteCreateObjectRequest request);
        
        // CODEGEN: Generating message contract since element name attr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttribute", ReplyAction="*")]
        OnlineShoping.ServiceReference1.GetAttributeResponse GetAttribute(OnlineShoping.ServiceReference1.GetAttributeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttribute", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.GetAttributeResponse> GetAttributeAsync(OnlineShoping.ServiceReference1.GetAttributeRequest request);
        
        // CODEGEN: Generating message contract since element name attr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAttribute", ReplyAction="*")]
        OnlineShoping.ServiceReference1.SetAttributeResponse SetAttribute(OnlineShoping.ServiceReference1.SetAttributeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAttribute", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.SetAttributeResponse> SetAttributeAsync(OnlineShoping.ServiceReference1.SetAttributeRequest request);
        
        // CODEGEN: Generating message contract since element name field from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        OnlineShoping.ServiceReference1.GetDataResponse GetData(OnlineShoping.ServiceReference1.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.GetDataResponse> GetDataAsync(OnlineShoping.ServiceReference1.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetData", ReplyAction="*")]
        OnlineShoping.ServiceReference1.SetDataResponse SetData(OnlineShoping.ServiceReference1.SetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetData", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.SetDataResponse> SetDataAsync(OnlineShoping.ServiceReference1.SetDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoteCreateObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoteCreateObject", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.ServiceReference1.RemoteCreateObjectRequestBody Body;
        
        public RemoteCreateObjectRequest() {
        }
        
        public RemoteCreateObjectRequest(OnlineShoping.ServiceReference1.RemoteCreateObjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoteCreateObjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public RemoteCreateObjectRequestBody() {
        }
        
        public RemoteCreateObjectRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoteCreateObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoteCreateObjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.ServiceReference1.RemoteCreateObjectResponseBody Body;
        
        public RemoteCreateObjectResponse() {
        }
        
        public RemoteCreateObjectResponse(OnlineShoping.ServiceReference1.RemoteCreateObjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoteCreateObjectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoteCreateObjectResult;
        
        public RemoteCreateObjectResponseBody() {
        }
        
        public RemoteCreateObjectResponseBody(int RemoteCreateObjectResult) {
            this.RemoteCreateObjectResult = RemoteCreateObjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttributeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttribute", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.ServiceReference1.GetAttributeRequestBody Body;
        
        public GetAttributeRequest() {
        }
        
        public GetAttributeRequest(OnlineShoping.ServiceReference1.GetAttributeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAttributeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int handle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string attr;
        
        public GetAttributeRequestBody() {
        }
        
        public GetAttributeRequestBody(int handle, string attr) {
            this.handle = handle;
            this.attr = attr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttributeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttributeResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.ServiceReference1.GetAttributeResponseBody Body;
        
        public GetAttributeResponse() {
        }
        
        public GetAttributeResponse(OnlineShoping.ServiceReference1.GetAttributeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAttributeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAttributeResult;
        
        public GetAttributeResponseBody() {
        }
        
        public GetAttributeResponseBody(string GetAttributeResult) {
            this.GetAttributeResult = GetAttributeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAttributeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAttribute", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.ServiceReference1.SetAttributeRequestBody Body;
        
        public SetAttributeRequest() {
        }
        
        public SetAttributeRequest(OnlineShoping.ServiceReference1.SetAttributeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAttributeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int handle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string attr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string value;
        
        public SetAttributeRequestBody() {
        }
        
        public SetAttributeRequestBody(int handle, string attr, string value) {
            this.handle = handle;
            this.attr = attr;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAttributeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAttributeResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.ServiceReference1.SetAttributeResponseBody Body;
        
        public SetAttributeResponse() {
        }
        
        public SetAttributeResponse(OnlineShoping.ServiceReference1.SetAttributeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAttributeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetAttributeResult;
        
        public SetAttributeResponseBody() {
        }
        
        public SetAttributeResponseBody(bool SetAttributeResult) {
            this.SetAttributeResult = SetAttributeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.ServiceReference1.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(OnlineShoping.ServiceReference1.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string condition;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string field, string tableName, string condition) {
            this.field = field;
            this.tableName = tableName;
            this.condition = condition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.ServiceReference1.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(OnlineShoping.ServiceReference1.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnlineShoping.ServiceReference1.ArrayOfInt GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(OnlineShoping.ServiceReference1.ArrayOfInt GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetData", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.ServiceReference1.SetDataRequestBody Body;
        
        public SetDataRequest() {
        }
        
        public SetDataRequest(OnlineShoping.ServiceReference1.SetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int handle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tableName;
        
        public SetDataRequestBody() {
        }
        
        public SetDataRequestBody(int handle, string tableName) {
            this.handle = handle;
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.ServiceReference1.SetDataResponseBody Body;
        
        public SetDataResponse() {
        }
        
        public SetDataResponse(OnlineShoping.ServiceReference1.SetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetDataResponseBody {
        
        public SetDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : OnlineShoping.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<OnlineShoping.ServiceReference1.WebServiceSoap>, OnlineShoping.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShoping.ServiceReference1.RemoteCreateObjectResponse OnlineShoping.ServiceReference1.WebServiceSoap.RemoteCreateObject(OnlineShoping.ServiceReference1.RemoteCreateObjectRequest request) {
            return base.Channel.RemoteCreateObject(request);
        }
        
        public int RemoteCreateObject(string name) {
            OnlineShoping.ServiceReference1.RemoteCreateObjectRequest inValue = new OnlineShoping.ServiceReference1.RemoteCreateObjectRequest();
            inValue.Body = new OnlineShoping.ServiceReference1.RemoteCreateObjectRequestBody();
            inValue.Body.name = name;
            OnlineShoping.ServiceReference1.RemoteCreateObjectResponse retVal = ((OnlineShoping.ServiceReference1.WebServiceSoap)(this)).RemoteCreateObject(inValue);
            return retVal.Body.RemoteCreateObjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.RemoteCreateObjectResponse> OnlineShoping.ServiceReference1.WebServiceSoap.RemoteCreateObjectAsync(OnlineShoping.ServiceReference1.RemoteCreateObjectRequest request) {
            return base.Channel.RemoteCreateObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.RemoteCreateObjectResponse> RemoteCreateObjectAsync(string name) {
            OnlineShoping.ServiceReference1.RemoteCreateObjectRequest inValue = new OnlineShoping.ServiceReference1.RemoteCreateObjectRequest();
            inValue.Body = new OnlineShoping.ServiceReference1.RemoteCreateObjectRequestBody();
            inValue.Body.name = name;
            return ((OnlineShoping.ServiceReference1.WebServiceSoap)(this)).RemoteCreateObjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShoping.ServiceReference1.GetAttributeResponse OnlineShoping.ServiceReference1.WebServiceSoap.GetAttribute(OnlineShoping.ServiceReference1.GetAttributeRequest request) {
            return base.Channel.GetAttribute(request);
        }
        
        public string GetAttribute(int handle, string attr) {
            OnlineShoping.ServiceReference1.GetAttributeRequest inValue = new OnlineShoping.ServiceReference1.GetAttributeRequest();
            inValue.Body = new OnlineShoping.ServiceReference1.GetAttributeRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.attr = attr;
            OnlineShoping.ServiceReference1.GetAttributeResponse retVal = ((OnlineShoping.ServiceReference1.WebServiceSoap)(this)).GetAttribute(inValue);
            return retVal.Body.GetAttributeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.GetAttributeResponse> OnlineShoping.ServiceReference1.WebServiceSoap.GetAttributeAsync(OnlineShoping.ServiceReference1.GetAttributeRequest request) {
            return base.Channel.GetAttributeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.GetAttributeResponse> GetAttributeAsync(int handle, string attr) {
            OnlineShoping.ServiceReference1.GetAttributeRequest inValue = new OnlineShoping.ServiceReference1.GetAttributeRequest();
            inValue.Body = new OnlineShoping.ServiceReference1.GetAttributeRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.attr = attr;
            return ((OnlineShoping.ServiceReference1.WebServiceSoap)(this)).GetAttributeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShoping.ServiceReference1.SetAttributeResponse OnlineShoping.ServiceReference1.WebServiceSoap.SetAttribute(OnlineShoping.ServiceReference1.SetAttributeRequest request) {
            return base.Channel.SetAttribute(request);
        }
        
        public bool SetAttribute(int handle, string attr, string value) {
            OnlineShoping.ServiceReference1.SetAttributeRequest inValue = new OnlineShoping.ServiceReference1.SetAttributeRequest();
            inValue.Body = new OnlineShoping.ServiceReference1.SetAttributeRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.attr = attr;
            inValue.Body.value = value;
            OnlineShoping.ServiceReference1.SetAttributeResponse retVal = ((OnlineShoping.ServiceReference1.WebServiceSoap)(this)).SetAttribute(inValue);
            return retVal.Body.SetAttributeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.SetAttributeResponse> OnlineShoping.ServiceReference1.WebServiceSoap.SetAttributeAsync(OnlineShoping.ServiceReference1.SetAttributeRequest request) {
            return base.Channel.SetAttributeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.SetAttributeResponse> SetAttributeAsync(int handle, string attr, string value) {
            OnlineShoping.ServiceReference1.SetAttributeRequest inValue = new OnlineShoping.ServiceReference1.SetAttributeRequest();
            inValue.Body = new OnlineShoping.ServiceReference1.SetAttributeRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.attr = attr;
            inValue.Body.value = value;
            return ((OnlineShoping.ServiceReference1.WebServiceSoap)(this)).SetAttributeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShoping.ServiceReference1.GetDataResponse OnlineShoping.ServiceReference1.WebServiceSoap.GetData(OnlineShoping.ServiceReference1.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public OnlineShoping.ServiceReference1.ArrayOfInt GetData(string field, string tableName, string condition) {
            OnlineShoping.ServiceReference1.GetDataRequest inValue = new OnlineShoping.ServiceReference1.GetDataRequest();
            inValue.Body = new OnlineShoping.ServiceReference1.GetDataRequestBody();
            inValue.Body.field = field;
            inValue.Body.tableName = tableName;
            inValue.Body.condition = condition;
            OnlineShoping.ServiceReference1.GetDataResponse retVal = ((OnlineShoping.ServiceReference1.WebServiceSoap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.GetDataResponse> OnlineShoping.ServiceReference1.WebServiceSoap.GetDataAsync(OnlineShoping.ServiceReference1.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.GetDataResponse> GetDataAsync(string field, string tableName, string condition) {
            OnlineShoping.ServiceReference1.GetDataRequest inValue = new OnlineShoping.ServiceReference1.GetDataRequest();
            inValue.Body = new OnlineShoping.ServiceReference1.GetDataRequestBody();
            inValue.Body.field = field;
            inValue.Body.tableName = tableName;
            inValue.Body.condition = condition;
            return ((OnlineShoping.ServiceReference1.WebServiceSoap)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShoping.ServiceReference1.SetDataResponse OnlineShoping.ServiceReference1.WebServiceSoap.SetData(OnlineShoping.ServiceReference1.SetDataRequest request) {
            return base.Channel.SetData(request);
        }
        
        public void SetData(int handle, string tableName) {
            OnlineShoping.ServiceReference1.SetDataRequest inValue = new OnlineShoping.ServiceReference1.SetDataRequest();
            inValue.Body = new OnlineShoping.ServiceReference1.SetDataRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.tableName = tableName;
            OnlineShoping.ServiceReference1.SetDataResponse retVal = ((OnlineShoping.ServiceReference1.WebServiceSoap)(this)).SetData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.SetDataResponse> OnlineShoping.ServiceReference1.WebServiceSoap.SetDataAsync(OnlineShoping.ServiceReference1.SetDataRequest request) {
            return base.Channel.SetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShoping.ServiceReference1.SetDataResponse> SetDataAsync(int handle, string tableName) {
            OnlineShoping.ServiceReference1.SetDataRequest inValue = new OnlineShoping.ServiceReference1.SetDataRequest();
            inValue.Body = new OnlineShoping.ServiceReference1.SetDataRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.tableName = tableName;
            return ((OnlineShoping.ServiceReference1.WebServiceSoap)(this)).SetDataAsync(inValue);
        }
    }
}
