//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoping.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllManufacturerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllManufacturer", ReplyAction="*")]
        OnlineShoping.WebService.GetAllManufacturerResponse GetAllManufacturer(OnlineShoping.WebService.GetAllManufacturerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllManufacturer", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShoping.WebService.GetAllManufacturerResponse> GetAllManufacturerAsync(OnlineShoping.WebService.GetAllManufacturerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllManufacturerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllManufacturer", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.WebService.GetAllManufacturerRequestBody Body;
        
        public GetAllManufacturerRequest() {
        }
        
        public GetAllManufacturerRequest(OnlineShoping.WebService.GetAllManufacturerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllManufacturerRequestBody {
        
        public GetAllManufacturerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllManufacturerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllManufacturerResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.WebService.GetAllManufacturerResponseBody Body;
        
        public GetAllManufacturerResponse() {
        }
        
        public GetAllManufacturerResponse(OnlineShoping.WebService.GetAllManufacturerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllManufacturerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllManufacturerResult;
        
        public GetAllManufacturerResponseBody() {
        }
        
        public GetAllManufacturerResponseBody(string GetAllManufacturerResult) {
            this.GetAllManufacturerResult = GetAllManufacturerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : OnlineShoping.WebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<OnlineShoping.WebService.WebServiceSoap>, OnlineShoping.WebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShoping.WebService.GetAllManufacturerResponse OnlineShoping.WebService.WebServiceSoap.GetAllManufacturer(OnlineShoping.WebService.GetAllManufacturerRequest request) {
            return base.Channel.GetAllManufacturer(request);
        }
        
        public string GetAllManufacturer() {
            OnlineShoping.WebService.GetAllManufacturerRequest inValue = new OnlineShoping.WebService.GetAllManufacturerRequest();
            inValue.Body = new OnlineShoping.WebService.GetAllManufacturerRequestBody();
            OnlineShoping.WebService.GetAllManufacturerResponse retVal = ((OnlineShoping.WebService.WebServiceSoap)(this)).GetAllManufacturer(inValue);
            return retVal.Body.GetAllManufacturerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShoping.WebService.GetAllManufacturerResponse> OnlineShoping.WebService.WebServiceSoap.GetAllManufacturerAsync(OnlineShoping.WebService.GetAllManufacturerRequest request) {
            return base.Channel.GetAllManufacturerAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShoping.WebService.GetAllManufacturerResponse> GetAllManufacturerAsync() {
            OnlineShoping.WebService.GetAllManufacturerRequest inValue = new OnlineShoping.WebService.GetAllManufacturerRequest();
            inValue.Body = new OnlineShoping.WebService.GetAllManufacturerRequestBody();
            return ((OnlineShoping.WebService.WebServiceSoap)(this)).GetAllManufacturerAsync(inValue);
        }
    }
}
