//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoping.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllManufacturerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllManufacturer", ReplyAction="*")]
        OnlineShoping.WebService.GetAllManufacturerResponse GetAllManufacturer(OnlineShoping.WebService.GetAllManufacturerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllManufacturer", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShoping.WebService.GetAllManufacturerResponse> GetAllManufacturerAsync(OnlineShoping.WebService.GetAllManufacturerRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        OnlineShoping.WebService.GetAllProductsResponse GetAllProducts(OnlineShoping.WebService.GetAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShoping.WebService.GetAllProductsResponse> GetAllProductsAsync(OnlineShoping.WebService.GetAllProductsRequest request);
        
        // CODEGEN: Generating message contract since element name field from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataFromTable", ReplyAction="*")]
        OnlineShoping.WebService.GetDataFromTableResponse GetDataFromTable(OnlineShoping.WebService.GetDataFromTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataFromTable", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShoping.WebService.GetDataFromTableResponse> GetDataFromTableAsync(OnlineShoping.WebService.GetDataFromTableRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetData", ReplyAction="*")]
        OnlineShoping.WebService.SetDataResponse SetData(OnlineShoping.WebService.SetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetData", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShoping.WebService.SetDataResponse> SetDataAsync(OnlineShoping.WebService.SetDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllManufacturerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllManufacturer", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.WebService.GetAllManufacturerRequestBody Body;
        
        public GetAllManufacturerRequest() {
        }
        
        public GetAllManufacturerRequest(OnlineShoping.WebService.GetAllManufacturerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllManufacturerRequestBody {
        
        public GetAllManufacturerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllManufacturerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllManufacturerResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.WebService.GetAllManufacturerResponseBody Body;
        
        public GetAllManufacturerResponse() {
        }
        
        public GetAllManufacturerResponse(OnlineShoping.WebService.GetAllManufacturerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllManufacturerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllManufacturerResult;
        
        public GetAllManufacturerResponseBody() {
        }
        
        public GetAllManufacturerResponseBody(string GetAllManufacturerResult) {
            this.GetAllManufacturerResult = GetAllManufacturerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProducts", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.WebService.GetAllProductsRequestBody Body;
        
        public GetAllProductsRequest() {
        }
        
        public GetAllProductsRequest(OnlineShoping.WebService.GetAllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProductsRequestBody {
        
        public GetAllProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.WebService.GetAllProductsResponseBody Body;
        
        public GetAllProductsResponse() {
        }
        
        public GetAllProductsResponse(OnlineShoping.WebService.GetAllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllProductsResult;
        
        public GetAllProductsResponseBody() {
        }
        
        public GetAllProductsResponseBody(string GetAllProductsResult) {
            this.GetAllProductsResult = GetAllProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataFromTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataFromTable", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.WebService.GetDataFromTableRequestBody Body;
        
        public GetDataFromTableRequest() {
        }
        
        public GetDataFromTableRequest(OnlineShoping.WebService.GetDataFromTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataFromTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string condition;
        
        public GetDataFromTableRequestBody() {
        }
        
        public GetDataFromTableRequestBody(string field, string tableName, string condition) {
            this.field = field;
            this.tableName = tableName;
            this.condition = condition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataFromTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataFromTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.WebService.GetDataFromTableResponseBody Body;
        
        public GetDataFromTableResponse() {
        }
        
        public GetDataFromTableResponse(OnlineShoping.WebService.GetDataFromTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataFromTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataFromTableResult;
        
        public GetDataFromTableResponseBody() {
        }
        
        public GetDataFromTableResponseBody(string GetDataFromTableResult) {
            this.GetDataFromTableResult = GetDataFromTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetData", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.WebService.SetDataRequestBody Body;
        
        public SetDataRequest() {
        }
        
        public SetDataRequest(OnlineShoping.WebService.SetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string attr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string value;
        
        public SetDataRequestBody() {
        }
        
        public SetDataRequestBody(string tableName, string attr, string value) {
            this.tableName = tableName;
            this.attr = attr;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShoping.WebService.SetDataResponseBody Body;
        
        public SetDataResponse() {
        }
        
        public SetDataResponse(OnlineShoping.WebService.SetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetDataResponseBody {
        
        public SetDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : OnlineShoping.WebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<OnlineShoping.WebService.WebServiceSoap>, OnlineShoping.WebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShoping.WebService.GetAllManufacturerResponse OnlineShoping.WebService.WebServiceSoap.GetAllManufacturer(OnlineShoping.WebService.GetAllManufacturerRequest request) {
            return base.Channel.GetAllManufacturer(request);
        }
        
        public string GetAllManufacturer() {
            OnlineShoping.WebService.GetAllManufacturerRequest inValue = new OnlineShoping.WebService.GetAllManufacturerRequest();
            inValue.Body = new OnlineShoping.WebService.GetAllManufacturerRequestBody();
            OnlineShoping.WebService.GetAllManufacturerResponse retVal = ((OnlineShoping.WebService.WebServiceSoap)(this)).GetAllManufacturer(inValue);
            return retVal.Body.GetAllManufacturerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShoping.WebService.GetAllManufacturerResponse> OnlineShoping.WebService.WebServiceSoap.GetAllManufacturerAsync(OnlineShoping.WebService.GetAllManufacturerRequest request) {
            return base.Channel.GetAllManufacturerAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShoping.WebService.GetAllManufacturerResponse> GetAllManufacturerAsync() {
            OnlineShoping.WebService.GetAllManufacturerRequest inValue = new OnlineShoping.WebService.GetAllManufacturerRequest();
            inValue.Body = new OnlineShoping.WebService.GetAllManufacturerRequestBody();
            return ((OnlineShoping.WebService.WebServiceSoap)(this)).GetAllManufacturerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShoping.WebService.GetAllProductsResponse OnlineShoping.WebService.WebServiceSoap.GetAllProducts(OnlineShoping.WebService.GetAllProductsRequest request) {
            return base.Channel.GetAllProducts(request);
        }
        
        public string GetAllProducts() {
            OnlineShoping.WebService.GetAllProductsRequest inValue = new OnlineShoping.WebService.GetAllProductsRequest();
            inValue.Body = new OnlineShoping.WebService.GetAllProductsRequestBody();
            OnlineShoping.WebService.GetAllProductsResponse retVal = ((OnlineShoping.WebService.WebServiceSoap)(this)).GetAllProducts(inValue);
            return retVal.Body.GetAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShoping.WebService.GetAllProductsResponse> OnlineShoping.WebService.WebServiceSoap.GetAllProductsAsync(OnlineShoping.WebService.GetAllProductsRequest request) {
            return base.Channel.GetAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShoping.WebService.GetAllProductsResponse> GetAllProductsAsync() {
            OnlineShoping.WebService.GetAllProductsRequest inValue = new OnlineShoping.WebService.GetAllProductsRequest();
            inValue.Body = new OnlineShoping.WebService.GetAllProductsRequestBody();
            return ((OnlineShoping.WebService.WebServiceSoap)(this)).GetAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShoping.WebService.GetDataFromTableResponse OnlineShoping.WebService.WebServiceSoap.GetDataFromTable(OnlineShoping.WebService.GetDataFromTableRequest request) {
            return base.Channel.GetDataFromTable(request);
        }
        
        public string GetDataFromTable(string field, string tableName, string condition) {
            OnlineShoping.WebService.GetDataFromTableRequest inValue = new OnlineShoping.WebService.GetDataFromTableRequest();
            inValue.Body = new OnlineShoping.WebService.GetDataFromTableRequestBody();
            inValue.Body.field = field;
            inValue.Body.tableName = tableName;
            inValue.Body.condition = condition;
            OnlineShoping.WebService.GetDataFromTableResponse retVal = ((OnlineShoping.WebService.WebServiceSoap)(this)).GetDataFromTable(inValue);
            return retVal.Body.GetDataFromTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShoping.WebService.GetDataFromTableResponse> OnlineShoping.WebService.WebServiceSoap.GetDataFromTableAsync(OnlineShoping.WebService.GetDataFromTableRequest request) {
            return base.Channel.GetDataFromTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShoping.WebService.GetDataFromTableResponse> GetDataFromTableAsync(string field, string tableName, string condition) {
            OnlineShoping.WebService.GetDataFromTableRequest inValue = new OnlineShoping.WebService.GetDataFromTableRequest();
            inValue.Body = new OnlineShoping.WebService.GetDataFromTableRequestBody();
            inValue.Body.field = field;
            inValue.Body.tableName = tableName;
            inValue.Body.condition = condition;
            return ((OnlineShoping.WebService.WebServiceSoap)(this)).GetDataFromTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShoping.WebService.SetDataResponse OnlineShoping.WebService.WebServiceSoap.SetData(OnlineShoping.WebService.SetDataRequest request) {
            return base.Channel.SetData(request);
        }
        
        public void SetData(string tableName, string attr, string value) {
            OnlineShoping.WebService.SetDataRequest inValue = new OnlineShoping.WebService.SetDataRequest();
            inValue.Body = new OnlineShoping.WebService.SetDataRequestBody();
            inValue.Body.tableName = tableName;
            inValue.Body.attr = attr;
            inValue.Body.value = value;
            OnlineShoping.WebService.SetDataResponse retVal = ((OnlineShoping.WebService.WebServiceSoap)(this)).SetData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShoping.WebService.SetDataResponse> OnlineShoping.WebService.WebServiceSoap.SetDataAsync(OnlineShoping.WebService.SetDataRequest request) {
            return base.Channel.SetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShoping.WebService.SetDataResponse> SetDataAsync(string tableName, string attr, string value) {
            OnlineShoping.WebService.SetDataRequest inValue = new OnlineShoping.WebService.SetDataRequest();
            inValue.Body = new OnlineShoping.WebService.SetDataRequestBody();
            inValue.Body.tableName = tableName;
            inValue.Body.attr = attr;
            inValue.Body.value = value;
            return ((OnlineShoping.WebService.WebServiceSoap)(this)).SetDataAsync(inValue);
        }
    }
}
