//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributedObject.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllManufacturerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllManufacturer", ReplyAction="*")]
        DistributedObject.Service.GetAllManufacturerResponse GetAllManufacturer(DistributedObject.Service.GetAllManufacturerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllManufacturer", ReplyAction="*")]
        System.Threading.Tasks.Task<DistributedObject.Service.GetAllManufacturerResponse> GetAllManufacturerAsync(DistributedObject.Service.GetAllManufacturerRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        DistributedObject.Service.GetAllProductsResponse GetAllProducts(DistributedObject.Service.GetAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<DistributedObject.Service.GetAllProductsResponse> GetAllProductsAsync(DistributedObject.Service.GetAllProductsRequest request);
        
        // CODEGEN: Generating message contract since element name field from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataFromTable", ReplyAction="*")]
        DistributedObject.Service.GetDataFromTableResponse GetDataFromTable(DistributedObject.Service.GetDataFromTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataFromTable", ReplyAction="*")]
        System.Threading.Tasks.Task<DistributedObject.Service.GetDataFromTableResponse> GetDataFromTableAsync(DistributedObject.Service.GetDataFromTableRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllManufacturerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllManufacturer", Namespace="http://tempuri.org/", Order=0)]
        public DistributedObject.Service.GetAllManufacturerRequestBody Body;
        
        public GetAllManufacturerRequest() {
        }
        
        public GetAllManufacturerRequest(DistributedObject.Service.GetAllManufacturerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllManufacturerRequestBody {
        
        public GetAllManufacturerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllManufacturerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllManufacturerResponse", Namespace="http://tempuri.org/", Order=0)]
        public DistributedObject.Service.GetAllManufacturerResponseBody Body;
        
        public GetAllManufacturerResponse() {
        }
        
        public GetAllManufacturerResponse(DistributedObject.Service.GetAllManufacturerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllManufacturerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllManufacturerResult;
        
        public GetAllManufacturerResponseBody() {
        }
        
        public GetAllManufacturerResponseBody(string GetAllManufacturerResult) {
            this.GetAllManufacturerResult = GetAllManufacturerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProducts", Namespace="http://tempuri.org/", Order=0)]
        public DistributedObject.Service.GetAllProductsRequestBody Body;
        
        public GetAllProductsRequest() {
        }
        
        public GetAllProductsRequest(DistributedObject.Service.GetAllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProductsRequestBody {
        
        public GetAllProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DistributedObject.Service.GetAllProductsResponseBody Body;
        
        public GetAllProductsResponse() {
        }
        
        public GetAllProductsResponse(DistributedObject.Service.GetAllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllProductsResult;
        
        public GetAllProductsResponseBody() {
        }
        
        public GetAllProductsResponseBody(string GetAllProductsResult) {
            this.GetAllProductsResult = GetAllProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataFromTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataFromTable", Namespace="http://tempuri.org/", Order=0)]
        public DistributedObject.Service.GetDataFromTableRequestBody Body;
        
        public GetDataFromTableRequest() {
        }
        
        public GetDataFromTableRequest(DistributedObject.Service.GetDataFromTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataFromTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string condition;
        
        public GetDataFromTableRequestBody() {
        }
        
        public GetDataFromTableRequestBody(string field, string tableName, string condition) {
            this.field = field;
            this.tableName = tableName;
            this.condition = condition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataFromTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataFromTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public DistributedObject.Service.GetDataFromTableResponseBody Body;
        
        public GetDataFromTableResponse() {
        }
        
        public GetDataFromTableResponse(DistributedObject.Service.GetDataFromTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataFromTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataFromTableResult;
        
        public GetDataFromTableResponseBody() {
        }
        
        public GetDataFromTableResponseBody(string GetDataFromTableResult) {
            this.GetDataFromTableResult = GetDataFromTableResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : DistributedObject.Service.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<DistributedObject.Service.WebServiceSoap>, DistributedObject.Service.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DistributedObject.Service.GetAllManufacturerResponse DistributedObject.Service.WebServiceSoap.GetAllManufacturer(DistributedObject.Service.GetAllManufacturerRequest request) {
            return base.Channel.GetAllManufacturer(request);
        }
        
        public string GetAllManufacturer() {
            DistributedObject.Service.GetAllManufacturerRequest inValue = new DistributedObject.Service.GetAllManufacturerRequest();
            inValue.Body = new DistributedObject.Service.GetAllManufacturerRequestBody();
            DistributedObject.Service.GetAllManufacturerResponse retVal = ((DistributedObject.Service.WebServiceSoap)(this)).GetAllManufacturer(inValue);
            return retVal.Body.GetAllManufacturerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DistributedObject.Service.GetAllManufacturerResponse> DistributedObject.Service.WebServiceSoap.GetAllManufacturerAsync(DistributedObject.Service.GetAllManufacturerRequest request) {
            return base.Channel.GetAllManufacturerAsync(request);
        }
        
        public System.Threading.Tasks.Task<DistributedObject.Service.GetAllManufacturerResponse> GetAllManufacturerAsync() {
            DistributedObject.Service.GetAllManufacturerRequest inValue = new DistributedObject.Service.GetAllManufacturerRequest();
            inValue.Body = new DistributedObject.Service.GetAllManufacturerRequestBody();
            return ((DistributedObject.Service.WebServiceSoap)(this)).GetAllManufacturerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DistributedObject.Service.GetAllProductsResponse DistributedObject.Service.WebServiceSoap.GetAllProducts(DistributedObject.Service.GetAllProductsRequest request) {
            return base.Channel.GetAllProducts(request);
        }
        
        public string GetAllProducts() {
            DistributedObject.Service.GetAllProductsRequest inValue = new DistributedObject.Service.GetAllProductsRequest();
            inValue.Body = new DistributedObject.Service.GetAllProductsRequestBody();
            DistributedObject.Service.GetAllProductsResponse retVal = ((DistributedObject.Service.WebServiceSoap)(this)).GetAllProducts(inValue);
            return retVal.Body.GetAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DistributedObject.Service.GetAllProductsResponse> DistributedObject.Service.WebServiceSoap.GetAllProductsAsync(DistributedObject.Service.GetAllProductsRequest request) {
            return base.Channel.GetAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DistributedObject.Service.GetAllProductsResponse> GetAllProductsAsync() {
            DistributedObject.Service.GetAllProductsRequest inValue = new DistributedObject.Service.GetAllProductsRequest();
            inValue.Body = new DistributedObject.Service.GetAllProductsRequestBody();
            return ((DistributedObject.Service.WebServiceSoap)(this)).GetAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DistributedObject.Service.GetDataFromTableResponse DistributedObject.Service.WebServiceSoap.GetDataFromTable(DistributedObject.Service.GetDataFromTableRequest request) {
            return base.Channel.GetDataFromTable(request);
        }
        
        public string GetDataFromTable(string field, string tableName, string condition) {
            DistributedObject.Service.GetDataFromTableRequest inValue = new DistributedObject.Service.GetDataFromTableRequest();
            inValue.Body = new DistributedObject.Service.GetDataFromTableRequestBody();
            inValue.Body.field = field;
            inValue.Body.tableName = tableName;
            inValue.Body.condition = condition;
            DistributedObject.Service.GetDataFromTableResponse retVal = ((DistributedObject.Service.WebServiceSoap)(this)).GetDataFromTable(inValue);
            return retVal.Body.GetDataFromTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DistributedObject.Service.GetDataFromTableResponse> DistributedObject.Service.WebServiceSoap.GetDataFromTableAsync(DistributedObject.Service.GetDataFromTableRequest request) {
            return base.Channel.GetDataFromTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<DistributedObject.Service.GetDataFromTableResponse> GetDataFromTableAsync(string field, string tableName, string condition) {
            DistributedObject.Service.GetDataFromTableRequest inValue = new DistributedObject.Service.GetDataFromTableRequest();
            inValue.Body = new DistributedObject.Service.GetDataFromTableRequestBody();
            inValue.Body.field = field;
            inValue.Body.tableName = tableName;
            inValue.Body.condition = condition;
            return ((DistributedObject.Service.WebServiceSoap)(this)).GetDataFromTableAsync(inValue);
        }
    }
}
