//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopingLib.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoteCreateObject", ReplyAction="*")]
        OnlineShopingLib.WebService.RemoteCreateObjectResponse RemoteCreateObject(OnlineShopingLib.WebService.RemoteCreateObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoteCreateObject", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.RemoteCreateObjectResponse> RemoteCreateObjectAsync(OnlineShopingLib.WebService.RemoteCreateObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DestroyObject", ReplyAction="*")]
        bool DestroyObject(int handle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DestroyObject", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DestroyObjectAsync(int handle);
        
        // CODEGEN: Generating message contract since element name attr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttribute", ReplyAction="*")]
        OnlineShopingLib.WebService.GetAttributeResponse GetAttribute(OnlineShopingLib.WebService.GetAttributeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttribute", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.GetAttributeResponse> GetAttributeAsync(OnlineShopingLib.WebService.GetAttributeRequest request);
        
        // CODEGEN: Generating message contract since element name attr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAttribute", ReplyAction="*")]
        OnlineShopingLib.WebService.SetAttributeResponse SetAttribute(OnlineShopingLib.WebService.SetAttributeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAttribute", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.SetAttributeResponse> SetAttributeAsync(OnlineShopingLib.WebService.SetAttributeRequest request);
        
        // CODEGEN: Generating message contract since element name field from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        OnlineShopingLib.WebService.GetDataResponse GetData(OnlineShopingLib.WebService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.GetDataResponse> GetDataAsync(OnlineShopingLib.WebService.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetData", ReplyAction="*")]
        OnlineShopingLib.WebService.SetDataResponse SetData(OnlineShopingLib.WebService.SetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetData", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.SetDataResponse> SetDataAsync(OnlineShopingLib.WebService.SetDataRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        OnlineShopingLib.WebService.DeleteResponse Delete(OnlineShopingLib.WebService.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.DeleteResponse> DeleteAsync(OnlineShopingLib.WebService.DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        OnlineShopingLib.WebService.UpdateResponse Update(OnlineShopingLib.WebService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.UpdateResponse> UpdateAsync(OnlineShopingLib.WebService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count", ReplyAction="*")]
        int Count();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CountAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoteCreateObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoteCreateObject", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.RemoteCreateObjectRequestBody Body;
        
        public RemoteCreateObjectRequest() {
        }
        
        public RemoteCreateObjectRequest(OnlineShopingLib.WebService.RemoteCreateObjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoteCreateObjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public RemoteCreateObjectRequestBody() {
        }
        
        public RemoteCreateObjectRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoteCreateObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoteCreateObjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.RemoteCreateObjectResponseBody Body;
        
        public RemoteCreateObjectResponse() {
        }
        
        public RemoteCreateObjectResponse(OnlineShopingLib.WebService.RemoteCreateObjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoteCreateObjectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoteCreateObjectResult;
        
        public RemoteCreateObjectResponseBody() {
        }
        
        public RemoteCreateObjectResponseBody(int RemoteCreateObjectResult) {
            this.RemoteCreateObjectResult = RemoteCreateObjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttributeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttribute", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.GetAttributeRequestBody Body;
        
        public GetAttributeRequest() {
        }
        
        public GetAttributeRequest(OnlineShopingLib.WebService.GetAttributeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAttributeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int handle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string attr;
        
        public GetAttributeRequestBody() {
        }
        
        public GetAttributeRequestBody(int handle, string attr) {
            this.handle = handle;
            this.attr = attr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttributeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttributeResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.GetAttributeResponseBody Body;
        
        public GetAttributeResponse() {
        }
        
        public GetAttributeResponse(OnlineShopingLib.WebService.GetAttributeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAttributeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAttributeResult;
        
        public GetAttributeResponseBody() {
        }
        
        public GetAttributeResponseBody(string GetAttributeResult) {
            this.GetAttributeResult = GetAttributeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAttributeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAttribute", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.SetAttributeRequestBody Body;
        
        public SetAttributeRequest() {
        }
        
        public SetAttributeRequest(OnlineShopingLib.WebService.SetAttributeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAttributeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int handle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string attr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string value;
        
        public SetAttributeRequestBody() {
        }
        
        public SetAttributeRequestBody(int handle, string attr, string value) {
            this.handle = handle;
            this.attr = attr;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAttributeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAttributeResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.SetAttributeResponseBody Body;
        
        public SetAttributeResponse() {
        }
        
        public SetAttributeResponse(OnlineShopingLib.WebService.SetAttributeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAttributeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetAttributeResult;
        
        public SetAttributeResponseBody() {
        }
        
        public SetAttributeResponseBody(bool SetAttributeResult) {
            this.SetAttributeResult = SetAttributeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(OnlineShopingLib.WebService.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string condition;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string field, string tableName, string condition) {
            this.field = field;
            this.tableName = tableName;
            this.condition = condition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(OnlineShopingLib.WebService.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnlineShopingLib.WebService.ArrayOfInt GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(OnlineShopingLib.WebService.ArrayOfInt GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetData", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.SetDataRequestBody Body;
        
        public SetDataRequest() {
        }
        
        public SetDataRequest(OnlineShopingLib.WebService.SetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int handle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tableName;
        
        public SetDataRequestBody() {
        }
        
        public SetDataRequestBody(int handle, string tableName) {
            this.handle = handle;
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.SetDataResponseBody Body;
        
        public SetDataResponse() {
        }
        
        public SetDataResponse(OnlineShopingLib.WebService.SetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetDataResponseBody {
        
        public SetDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(OnlineShopingLib.WebService.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int handle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string attr;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(int handle, string tableName, string attr) {
            this.handle = handle;
            this.tableName = tableName;
            this.attr = attr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(OnlineShopingLib.WebService.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteResponseBody {
        
        public DeleteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(OnlineShopingLib.WebService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int handle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string condition;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(int handle, string tableName, string condition) {
            this.handle = handle;
            this.tableName = tableName;
            this.condition = condition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineShopingLib.WebService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(OnlineShopingLib.WebService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : OnlineShopingLib.WebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<OnlineShopingLib.WebService.WebServiceSoap>, OnlineShopingLib.WebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShopingLib.WebService.RemoteCreateObjectResponse OnlineShopingLib.WebService.WebServiceSoap.RemoteCreateObject(OnlineShopingLib.WebService.RemoteCreateObjectRequest request) {
            return base.Channel.RemoteCreateObject(request);
        }
        
        public int RemoteCreateObject(string name) {
            OnlineShopingLib.WebService.RemoteCreateObjectRequest inValue = new OnlineShopingLib.WebService.RemoteCreateObjectRequest();
            inValue.Body = new OnlineShopingLib.WebService.RemoteCreateObjectRequestBody();
            inValue.Body.name = name;
            OnlineShopingLib.WebService.RemoteCreateObjectResponse retVal = ((OnlineShopingLib.WebService.WebServiceSoap)(this)).RemoteCreateObject(inValue);
            return retVal.Body.RemoteCreateObjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.RemoteCreateObjectResponse> OnlineShopingLib.WebService.WebServiceSoap.RemoteCreateObjectAsync(OnlineShopingLib.WebService.RemoteCreateObjectRequest request) {
            return base.Channel.RemoteCreateObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShopingLib.WebService.RemoteCreateObjectResponse> RemoteCreateObjectAsync(string name) {
            OnlineShopingLib.WebService.RemoteCreateObjectRequest inValue = new OnlineShopingLib.WebService.RemoteCreateObjectRequest();
            inValue.Body = new OnlineShopingLib.WebService.RemoteCreateObjectRequestBody();
            inValue.Body.name = name;
            return ((OnlineShopingLib.WebService.WebServiceSoap)(this)).RemoteCreateObjectAsync(inValue);
        }
        
        public bool DestroyObject(int handle) {
            return base.Channel.DestroyObject(handle);
        }
        
        public System.Threading.Tasks.Task<bool> DestroyObjectAsync(int handle) {
            return base.Channel.DestroyObjectAsync(handle);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShopingLib.WebService.GetAttributeResponse OnlineShopingLib.WebService.WebServiceSoap.GetAttribute(OnlineShopingLib.WebService.GetAttributeRequest request) {
            return base.Channel.GetAttribute(request);
        }
        
        public string GetAttribute(int handle, string attr) {
            OnlineShopingLib.WebService.GetAttributeRequest inValue = new OnlineShopingLib.WebService.GetAttributeRequest();
            inValue.Body = new OnlineShopingLib.WebService.GetAttributeRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.attr = attr;
            OnlineShopingLib.WebService.GetAttributeResponse retVal = ((OnlineShopingLib.WebService.WebServiceSoap)(this)).GetAttribute(inValue);
            return retVal.Body.GetAttributeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.GetAttributeResponse> OnlineShopingLib.WebService.WebServiceSoap.GetAttributeAsync(OnlineShopingLib.WebService.GetAttributeRequest request) {
            return base.Channel.GetAttributeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShopingLib.WebService.GetAttributeResponse> GetAttributeAsync(int handle, string attr) {
            OnlineShopingLib.WebService.GetAttributeRequest inValue = new OnlineShopingLib.WebService.GetAttributeRequest();
            inValue.Body = new OnlineShopingLib.WebService.GetAttributeRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.attr = attr;
            return ((OnlineShopingLib.WebService.WebServiceSoap)(this)).GetAttributeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShopingLib.WebService.SetAttributeResponse OnlineShopingLib.WebService.WebServiceSoap.SetAttribute(OnlineShopingLib.WebService.SetAttributeRequest request) {
            return base.Channel.SetAttribute(request);
        }
        
        public bool SetAttribute(int handle, string attr, string value) {
            OnlineShopingLib.WebService.SetAttributeRequest inValue = new OnlineShopingLib.WebService.SetAttributeRequest();
            inValue.Body = new OnlineShopingLib.WebService.SetAttributeRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.attr = attr;
            inValue.Body.value = value;
            OnlineShopingLib.WebService.SetAttributeResponse retVal = ((OnlineShopingLib.WebService.WebServiceSoap)(this)).SetAttribute(inValue);
            return retVal.Body.SetAttributeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.SetAttributeResponse> OnlineShopingLib.WebService.WebServiceSoap.SetAttributeAsync(OnlineShopingLib.WebService.SetAttributeRequest request) {
            return base.Channel.SetAttributeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShopingLib.WebService.SetAttributeResponse> SetAttributeAsync(int handle, string attr, string value) {
            OnlineShopingLib.WebService.SetAttributeRequest inValue = new OnlineShopingLib.WebService.SetAttributeRequest();
            inValue.Body = new OnlineShopingLib.WebService.SetAttributeRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.attr = attr;
            inValue.Body.value = value;
            return ((OnlineShopingLib.WebService.WebServiceSoap)(this)).SetAttributeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShopingLib.WebService.GetDataResponse OnlineShopingLib.WebService.WebServiceSoap.GetData(OnlineShopingLib.WebService.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public OnlineShopingLib.WebService.ArrayOfInt GetData(string field, string tableName, string condition) {
            OnlineShopingLib.WebService.GetDataRequest inValue = new OnlineShopingLib.WebService.GetDataRequest();
            inValue.Body = new OnlineShopingLib.WebService.GetDataRequestBody();
            inValue.Body.field = field;
            inValue.Body.tableName = tableName;
            inValue.Body.condition = condition;
            OnlineShopingLib.WebService.GetDataResponse retVal = ((OnlineShopingLib.WebService.WebServiceSoap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.GetDataResponse> OnlineShopingLib.WebService.WebServiceSoap.GetDataAsync(OnlineShopingLib.WebService.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShopingLib.WebService.GetDataResponse> GetDataAsync(string field, string tableName, string condition) {
            OnlineShopingLib.WebService.GetDataRequest inValue = new OnlineShopingLib.WebService.GetDataRequest();
            inValue.Body = new OnlineShopingLib.WebService.GetDataRequestBody();
            inValue.Body.field = field;
            inValue.Body.tableName = tableName;
            inValue.Body.condition = condition;
            return ((OnlineShopingLib.WebService.WebServiceSoap)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShopingLib.WebService.SetDataResponse OnlineShopingLib.WebService.WebServiceSoap.SetData(OnlineShopingLib.WebService.SetDataRequest request) {
            return base.Channel.SetData(request);
        }
        
        public void SetData(int handle, string tableName) {
            OnlineShopingLib.WebService.SetDataRequest inValue = new OnlineShopingLib.WebService.SetDataRequest();
            inValue.Body = new OnlineShopingLib.WebService.SetDataRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.tableName = tableName;
            OnlineShopingLib.WebService.SetDataResponse retVal = ((OnlineShopingLib.WebService.WebServiceSoap)(this)).SetData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.SetDataResponse> OnlineShopingLib.WebService.WebServiceSoap.SetDataAsync(OnlineShopingLib.WebService.SetDataRequest request) {
            return base.Channel.SetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShopingLib.WebService.SetDataResponse> SetDataAsync(int handle, string tableName) {
            OnlineShopingLib.WebService.SetDataRequest inValue = new OnlineShopingLib.WebService.SetDataRequest();
            inValue.Body = new OnlineShopingLib.WebService.SetDataRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.tableName = tableName;
            return ((OnlineShopingLib.WebService.WebServiceSoap)(this)).SetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShopingLib.WebService.DeleteResponse OnlineShopingLib.WebService.WebServiceSoap.Delete(OnlineShopingLib.WebService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public void Delete(int handle, string tableName, string attr) {
            OnlineShopingLib.WebService.DeleteRequest inValue = new OnlineShopingLib.WebService.DeleteRequest();
            inValue.Body = new OnlineShopingLib.WebService.DeleteRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.tableName = tableName;
            inValue.Body.attr = attr;
            OnlineShopingLib.WebService.DeleteResponse retVal = ((OnlineShopingLib.WebService.WebServiceSoap)(this)).Delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.DeleteResponse> OnlineShopingLib.WebService.WebServiceSoap.DeleteAsync(OnlineShopingLib.WebService.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShopingLib.WebService.DeleteResponse> DeleteAsync(int handle, string tableName, string attr) {
            OnlineShopingLib.WebService.DeleteRequest inValue = new OnlineShopingLib.WebService.DeleteRequest();
            inValue.Body = new OnlineShopingLib.WebService.DeleteRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.tableName = tableName;
            inValue.Body.attr = attr;
            return ((OnlineShopingLib.WebService.WebServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineShopingLib.WebService.UpdateResponse OnlineShopingLib.WebService.WebServiceSoap.Update(OnlineShopingLib.WebService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(int handle, string tableName, string condition) {
            OnlineShopingLib.WebService.UpdateRequest inValue = new OnlineShopingLib.WebService.UpdateRequest();
            inValue.Body = new OnlineShopingLib.WebService.UpdateRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.tableName = tableName;
            inValue.Body.condition = condition;
            OnlineShopingLib.WebService.UpdateResponse retVal = ((OnlineShopingLib.WebService.WebServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineShopingLib.WebService.UpdateResponse> OnlineShopingLib.WebService.WebServiceSoap.UpdateAsync(OnlineShopingLib.WebService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineShopingLib.WebService.UpdateResponse> UpdateAsync(int handle, string tableName, string condition) {
            OnlineShopingLib.WebService.UpdateRequest inValue = new OnlineShopingLib.WebService.UpdateRequest();
            inValue.Body = new OnlineShopingLib.WebService.UpdateRequestBody();
            inValue.Body.handle = handle;
            inValue.Body.tableName = tableName;
            inValue.Body.condition = condition;
            return ((OnlineShopingLib.WebService.WebServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public int Count() {
            return base.Channel.Count();
        }
        
        public System.Threading.Tasks.Task<int> CountAsync() {
            return base.Channel.CountAsync();
        }
    }
}
